ssync snonsyn msync mnonsync: thread_nonsync.c thread_sync.c  mutex_thread_nonsync.c  mutext_thread_sync.c
	gcc thread_nonsync.c -o snonsync
	gcc thread_sync.c -o ssync
	gcc mutex_thread_nonsync.c -o mnonsync 
	gcc  mutext_thread_sync.c  -o msync
 
